apiVersion: v2
name: my-application
description: A Helm chart for my application
type: application
version: 1.0.0
appVersion: "2.0.0"

dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
  - name: nginx-ingress-controller
    version: "9.9.2"
    repository: "https://charts.bitnami.com/bitnami"
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
